version: '3.8'

services:
  f_laravel:
    image: image_f_laravel
    container_name: f_laravel
    build:
      context: .
      dockerfile: db.dockerfile
    volumes:
      - .:/app
      - vendor_data:/app/vendor
    env_file: # <-- KUNCI KEBERHASILAN ANDA UNTUK LARAVEL
      - .env
    # environment: # <-- Ini dikomentari, berarti env_file adalah metode utama
    networks:
      - app_network
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: unless-stopped

  caddy:
    image: caddy:2.7.5-alpine
    container_name: caddy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - ./public:/app/public
      - caddy_data:/data
    networks:
      - app_network
    depends_on:
      - f_laravel

  db:
    image: mariadb:10.11
    container_name: laravel_db
    restart: unless-stopped
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
      MYSQL_ROOT_PASSWORD: ${APP_ROOT_PASSWORD}
    # MYSQL_DATABASE: ${DB_NAME} # <-- Ini dikomentari
    # MYSQL_USER: ${DB_USER} # <-- Ini dikomentari
    # MYSQL_PASSWORD: ${APP_DB_PASSWORD} # <-- Ini dikomentari
    volumes:
      - db_data:/var/lib/mysql
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d/
    networks:
      - app_network
    healthcheck: # <-- Health check yang sudah diperbaiki
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${APP_ROOT_PASSWORD}"]
      timeout: 20s
      retries: 10
      interval: 5s
      start_period: 30s

  redis:
    image: redis:7.2-alpine
    container_name: laravel_redis
    restart: unless-stopped
    networks:
      - app_network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 1s
      timeout: 3s
      retries: 30

volumes:
  vendor_data:
  caddy_data:
  db_data:

networks:
  app_network:
    driver: bridge
